source 'https://rubygems.org'

gem 'berkshelf', '~> 2.0'
gem 'chef', '~> 11.6'
gem 'chefspec', '~> 2.0'
gem 'foodcritic', '~> 3.0'
gem 'minitest', '~> 4.7'
gem 'minitest-chef-handler', '~> 1.0'
gem 'rake', '~> 10'
gem 'rspec', '~> 2.14'
